### ISSUE TITLE
How to use DecoPath in my python scripts?

### ISSUE THREAD

**Issue by hellowangqian** [DecoPath/DecoPath#3]
Dear authors，
First of all, I'd like to thank you for sharing such a great work to the community. The web UI is nice and convenient to use in most cases but I'm wondering if there are options to use it in the command line or to call the GSEA funcitons from my python programe. If possible, it'll be much appreciated to get some hints for such purposes. 
Best,
Qian

**Comment by ddomingof** [comment]
Hi Qian,
To do this you have to dig in a bit in the src/ functions
For example, here is the ORA function (https://github.com/DecoPath/DecoPath/blob/main/viewer/src/ora.py)
